spring:
  application:
    name: Delivery

  datasource:
    url: jdbc:postgresql://localhost:5432/delivery
    username: DB_USERNAME
    password: DB_PASSWORD
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect